### ISSUE TITLE
Criar tela de listagem de livros

### ISSUE THREAD

**Issue by jpmartins201** [LucasVeloz/Livro-Livre#5]
## Listagem de livros
Eu, como aluno/anônimo, quero encontrar os livros de um autor ou com um título específico para melhorar minha busca dentro do Livro Livre.

**Critérios de aceitação**
- A listagem deve ser feita a partir da barra de busca na tela inicial;
- O usuário pode informar o título, nome do autor ou ano de publicação (ex. '2024');

**Comment by italomarcos1** [comment]
Finalizado. Segue o PR:
https://github.com/LucasVeloz/Livro-Livre/pull/13
